// Which 3D body a MUD creature gets, from words in its name or description (looks.js decides
// which words to try first). First match wins. The cute monsters are
// mostly one big head, so they stay around half the hero's height (the KayKit hero is ~2.4 m). Models are the
// Quaternius creatures in art3d/mobs (built 1 m tall, scaled here to `h` metres), or a
// procedural body from proc.js for staples no free pack covers (rats, spiders, snakes,
// rabbits, slimes). `fly` lifts flyers off the ground; `tint` recolours untextured models.
// `person` entries use a KayKit adventurer (constructs, statues, folk with their own skin);
// `prop` a kit model (a mimic is a chest), `h` being its longest side. Undead and people by
// trade are in looks.js.
export const BESTIARY = [
  // things that are not animals at all: constructs, elementals, animated objects, plants
  [/\b(statue|statues|caryatid)\b/, { person: 'knight', loadout: [], tint: 0xb8b4ac, scale: 1.35, still: true, flat: true }],
  [/\b(golem|golems|construct|juggernaut|bulwark|automaton|clockwork)\b/, { person: 'knight', loadout: ['Knight_Helmet'], material: true, scale: 1.4, flat: true }],
  [/\b(training dummy|dummy|scarecrow)\b/, { person: 'rogue', loadout: [], tint: 0xc8a878, still: true, flat: true }],
  [/\b(suit of armou?r|animated armou?r|living armou?r|possessed armou?r|empty armou?r|haunted armou?r)\b/, { person: 'knight', loadout: ['1H_Sword', 'Round_Shield', 'Knight_Helmet'], material: true, flat: true }],
  [/\b(furnace|voidglass|null-ward) sentinels?\b/, { person: 'knight', loadout: ['1H_Sword', 'Rectangle_Shield', 'Knight_Helmet'], material: true, scale: 1.3, flat: true }],
  [/\bmagma reaver\b/, { person: 'barbarian', loadout: ['2H_Axe'], tint: 0xc86a3a, scale: 1.3 }],
  [/\b(magma|lava) crawlers?\b/, { proc: 'snake', h: 1.0, tint: 0xc85a2a }],
  [/\bfractureblade stalker\b/, { person: 'rogue_hooded', loadout: ['Knife', 'Knife_Offhand'], tint: 0x3a3a48 }],
  // chess pieces come to life, black or white
  [/\b(pawn|pawns)\b/, { person: 'knight', loadout: ['1H_Sword', 'Knight_Helmet'], material: true, scale: 0.85, flat: true }],
  [/\b(rook|rooks)\b/, { person: 'knight', loadout: ['Rectangle_Shield', 'Knight_Helmet'], material: true, scale: 1.3, flat: true }],
  [/\b(black|white) bishops?\b/, { person: 'mage', loadout: ['2H_Staff', 'Mage_Hat'], material: true, flat: true }],
  [/\b(black|white) (knights?|queens?|kings?)\b/, { person: 'knight', loadout: ['1H_Sword', 'Badge_Shield', 'Knight_Helmet', 'Knight_Cape'], material: true, flat: true }],
  // people-shaped folk with their own skin
  [/\b(lizardfolk|lizardman|lizardmen|lizard man|lizard men|lizard-man|troglodytes?|kuo-toa|bullywugs?)\b/, { person: 'barbarian', loadout: ['1H_Axe', 'Barbarian_Round_Shield'], tint: 0x8ab070 }],
  [/\b(merman|mermen|mermaids?|merfolk|merrow|tritons?|nereids?)\b/, { person: 'rogue', loadout: ['Knife'], tint: 0x8ac8c0 }],
  [/\b(hag|hags|crone|crones)\b/, { person: 'mage', loadout: ['1H_Wand', 'Mage_Hat'], tint: 0x9ab080 }],
  [/\b(pixie|pixies|sprite|sprites|fairy|fairies|faerie|nixie|brownie)\b/, { person: 'mage', loadout: ['1H_Wand'], tint: 0xd8f0c0, scale: 0.42, fly: 0.9 }],
  [/\b(efreeti|efreet|ifrit|ifreet)\b/, { mob: 'ghost', h: 2.0, tint: 0xff8a3a, fly: 0.4 }],
  [/\b(djinn|djinni|genie|marid|jinn)\b/, { mob: 'ghost', h: 2.0, tint: 0x6ab8ff, fly: 0.4 }],
  [/\b(fire elemental|flame elemental|magma|scoria|salamander king)\b/, { mob: 'ghost', h: 1.7, tint: 0xff7a2a, fly: 0.2 }],
  [/\b(water elemental|tide elemental|wave elemental)\b/, { mob: 'ghost', h: 1.7, tint: 0x4a9aff, fly: 0.2 }],
  [/\b(ice elemental|frost elemental|crystallized|crystal elemental)\b/, { mob: 'ghost', h: 1.7, tint: 0x9fd8ff, fly: 0.2 }],
  [/\b(earth elemental|dirt devil|sandman|sand elemental|mud elemental)\b/, { mob: 'yeti', h: 1.9, tint: 0x9a7a54 }],
  [/\b(air elemental|aerial servant|wind elemental|cloud elemental)\b/, { mob: 'ghost', h: 1.7, tint: 0xe8f4ff, fly: 0.4 }],
  [/\b(chaos elemental|elemental)\b/, { mob: 'ghost', h: 1.7, tint: 0xc87aff, fly: 0.2 }],
  [/\bmimic\b/, { prop: ['dungeon', 'chest'], h: 0.9 }],
  [/\b(book monster|living book|tome)\b/, { prop: ['furniture', 'book_single'], h: 0.6, fly: 1.0 }],
  [/\b(dancing sword|flying sword|animated sword|blade)\b/, { prop: ['dungeon', 'sword_shield'], h: 1.1, fly: 0.6 }],
  [/\b(magic carpet|flying carpet|carpet)\b/, { prop: ['furniture', 'rug_rectangle_stripes_A'], h: 1.8, fly: 0.9 }],
  [/\b(broom)\b/, { prop: ['graveyard', 'post'], h: 1.3, fly: 0.3 }],
  [/\b(disembodied eyes?|floating eye|eyeball|eyes)\b/, { mob: 'alien', h: 0.8, fly: 0.9 }],
  [/\b(disembodied hands?|hands)\b/, { mob: 'ghost', h: 0.8, tint: 0xe8d8c8, fly: 0.7 }],
  [/\b(drone|tesla|coil|sentry gun)\b/, { mob: 'skull', h: 0.8, tint: 0x9aa8b8, fly: 1.0 }],
  [/\b(ancient tree|oakfather|treant|ent|dryad|walking tree|tree spirit|tree)\b/, { mob: 'tree', h: 2.8 }],
  [/\b(thornvine|vine|creeper|shambling mound|bramble)\b/, { mob: 'tree', h: 1.6, tint: 0x6a9a4a }],
  [/\b(myconid|myconoid|fungus|fungi|shroom|toadstool|sporeling|mushroom)\b/, { mob: 'mushroom', h: 1.0 }],
  // oozes and blobs
  [/\b(mudmonster|mud monster|mud)\b/, { proc: 'slime', h: 1.4, tint: 0x7a5a3a }],
  [/\b(slime|slimeball|ooze|jelly|blob|pudding|gelatinous|lemure|yochlol|pit beast|dustdigger|cube)\b/, { proc: 'slime', h: 0.85 }],
  // crawling things (not bees)
  [/\b(drider|driders)\b/, { proc: 'spider', h: 1.4, tint: 0x4a3a5a }],
  [/\b(spider|spiders|arachnid|tarantula|broodmother|spiderling|spinner|cleaver|reaver)\b/, { proc: 'spider', h: 0.8 }],
  [/\b(beetle|beetles|scarab|cockroach|roach|crawler|tick|ant|ants)\b/, { proc: 'spider', h: 0.5, tint: 0x5a4030 }],
  [/\b(centipede|millipede|maggot|maggots|worm|worms|larva|grub|leech|sandworm)\b/, { proc: 'snake', h: 0.5, tint: 0xc8b89a }],
  [/\b(crocodile|alligator|croc|gator)\b/, { proc: 'lizard', h: 1.6, tint: 0x4a6a3a }],
  [/\b(minotaur lizard|monitor lizard|giant lizard)\b/, { proc: 'lizard', h: 1.9, tint: 0x7a6a3a }],
  [/\b(basilisk|basilisks)\b/, { proc: 'lizard', h: 1.8, tint: 0x6a8a5a }],
  [/\b(behir|hydra|cryohydra|thornback|lamia|naga)\b/, { proc: 'snake', h: 1.1, tint: 0x6a8a5a }],
  [/\b(couatl)\b/, { proc: 'snake', h: 0.9, tint: 0x5ab88a, fly: 1.2 }],
  [/\b(wererats?|ratman|ratmen|rat-man)\b/, { proc: 'rat', h: 1.0, tint: 0x6a5a50 }],
  [/\b(werewolf|werewolves|lycanthropes?|wolfman|wolf-man)\b/, { mob: 'wolf', h: 1.45, tint: 0x5a5048 }],
  [/\b(rat|rats|mouse|mice|rodent|vermin|giant rat)\b/, { proc: 'rat', h: 0.42 }],
  [/\b(squirrel|chipmunk|weasel|ferret|stoat|badger|otter|mole|hedgehog|porcupine|raccoon|skunk|beaver|marmot|vole|shrew|mongoose|wolverine)\b/, { proc: 'rat', h: 0.45, tint: 0x9a6a44 }],
  [/\b(sea serpent|sea serpents|sea snake)\b/, { proc: 'snake', h: 1.4, tint: 0x3a7a8a }],
  [/\bdragon turtle\b/, { mob: 'yellowdragon', h: 2.6, tint: 0x4a8a6a }],
  [/\b(turtle|turtles|tortoise|terrapin)\b/, { mob: 'crab', h: 0.6, tint: 0x6a8a4a }],
  [/\b(lizard|lizards|salamander|newt|gecko|iguana|skink)\b/, { proc: 'lizard', h: 0.55 }],
  [/\b(snake|snakes|serpent|viper|asp|cobra|adder|python|anaconda|rattlesnake)\b/, { proc: 'snake', h: 0.45 }],
  [/\b(rabbit|rabbits|bunny|hare|jackrabbit|woundwort)\b/, { proc: 'rabbit', h: 0.5 }],
  [/\b(frog|toad|frogs|toads)\b/, { proc: 'slime', h: 0.6, tint: 0x6a9a4a }],
  [/\b(bat|bats|vampire bat)\b/, { mob: 'bat', h: 0.75, fly: 1.3 }],
  [/\b(shadow beast|nightmare beast|stalker|shadow hound|hell ?hounds?|barghest)\b/, { mob: 'wolf', h: 1.25, tint: 0x2e2a36 }],
  [/\b(wolf|wolves|warg|worg|direwolf)\b/, { mob: 'wolf', h: 1.0, tint: 0x8d93a0 }],
  [/\b(fox|foxes|vixen)\b/, { mob: 'fox', h: 0.7, tint: 0xd6732c }],
  [/\b(jackal|coyote|hyena)\b/, { mob: 'wolf', h: 0.85, tint: 0xbf9e6c }],
  [/\b(pug)\b/, { mob: 'pug', h: 0.55 }],
  [/\b(dog|dogs|hound|hounds|puppy|mastiff|cur|mongrel|wolfhound|beagle|rottweiler|terrier|fido|odif)\b/, { mob: 'dog', h: 0.85, tint: 0x9c6c44 }],
  [/\b(cat|cats|kitten|wildcat|alley cat)\b/, { mob: 'cat', h: 0.55, tint: 0xc78e52 }],
  [/\b(sphinx|androsphinx|criosphinx|gynosphinx|hieracosphinx)\b/, { mob: 'cat', h: 1.9, tint: 0xd6bd86 }],
  [/\b(chimera|manticore)\b/, { mob: 'cat', h: 1.7, tint: 0xb08850 }],
  [/\b(lynx|bobcat|panther|cougar|puma|lion|lioness|tiger|leopard|jaguar|sabretooth)\b/, { mob: 'cat', h: 1.15, tint: 0xd9a050 }],
  [/\bpanda\b/, { mob: 'panda', h: 1.1 }],
  [/\b(bear|bears|grizzly|ursine|bearcub|cub)\b/, { mob: 'panda', h: 1.25, tint: 0x8a5a34 }],
  [/\b(deer|doe|fawn|stag|buck|elk|moose|reindeer|hart|antelope|gazelle)\b/, { mob: 'deer', h: 1.15 }],
  [/\b(cow|cows|bull|ox|oxen|cattle|calf|bison|buffalo|yak)\b/, { mob: 'cow', h: 1.45 }],
  [/\bzebra\b/, { mob: 'zebra', h: 1.6 }],
  [/\b(pegasus|unicorn)\b/, { mob: 'horse', h: 1.8, tint: 0xf4f0ec }],
  [/\b(ki-rin|kirin)\b/, { mob: 'horse', h: 1.9, tint: 0xffd86a, fly: 0.4 }],
  [/\bworst nightmare\b/, { mob: 'ghost', h: 1.6, fly: 0.3, tint: 0x4a3a6a }],
  [/\bnightmare\b/, { mob: 'horse', h: 1.8, tint: 0x2a2830 }],
  [/\b(horse|horses|pony|mare|stallion|steed|colt|mule|donkey|nag|warhorse)\b/, { mob: 'horse', h: 1.75 }],
  [/\b(llama|alpaca|camel)\b/, { mob: 'llama', h: 1.6 }],
  [/\b(boar|warthog|razorback)\b/, { mob: 'farm_pig', h: 1.0, tint: 0x9a7466 }],
  [/\b(pig|pigs|hog|swine|sow|piglet)\b/, { mob: 'farm_pig', h: 0.95 }],
  [/\b(sheep|lamb|ram|ewe|goat|goats)\b/, { mob: 'sheep', h: 1.05 }],
  [/\b(chicken|chickens|hen|rooster|cockerel|fowl)\b/, { mob: 'chicken', h: 0.5 }],
  [/\b(chick|chicks|duckling|gosling|cygnet)\b/, { mob: 'chick', h: 0.35 }],
  [/\b(swan|swans|goose|geese|duck|ducks|heron|stork|crane)\b/, { mob: 'bird', h: 0.6, tint: 0xf4f2ee }],
  [/\b(harpy|harpies|homba)\b/, { mob: 'eagle', h: 1.1, fly: 1.4, tint: 0xc8a888 }],
  [/\b(eagle|hawk|falcon|kestrel|vulture|condor|griffon|gryphon|roc)\b/, { mob: 'eagle', h: 0.75, fly: 1.6 }],
  [/\b(bird|birds|crow|crows|raven|ravens|sparrow|robin|songbird|pigeon|dove|owl|magpie|jay|finch|gull|seagull|parrot|bluebird|blackbird)\b/, { mob: 'bird', h: 0.45, fly: 1.3 }],
  [/\b(penguin|puffin)\b/, { mob: 'penguin', h: 0.7 }],
  [/\bpiranha\b/, { mob: 'piranha', h: 0.55 }],
  [/\b(shark|barracuda)\b/, { mob: 'piranha', h: 1.2, tint: 0x8a96a8 }],
  [/\b(whale|leviathan|orca)\b/, { mob: 'whale', h: 2.4 }],
  [/\b(ixitxachitl|manta|ray)\b/, { mob: 'fish', h: 0.9, tint: 0x5a4a6a }],
  [/\b(eel|eels|moray)\b/, { proc: 'snake', h: 0.4, tint: 0x4a6a8a }],
  [/\b(fish|trout|salmon|carp|perch|bass|pike|catfish|minnow)\b/, { mob: 'fish', h: 0.45, tint: 0x7fa8c8 }],
  [/\b(crab|crabs|lobster|crawfish|crayfish|scorpion)\b/, { mob: 'crab', h: 0.7 }],
  [/\b(bee|bees|wasp|wasps|hornet|hornets|insect|fly|flies|mosquito|dragonfly|moth|locust|firefly|butterfly)\b/, { mob: 'bee', h: 0.6, fly: 1.2 }],
  [/\b(dracolich)\b/, { mob: 'yellowdragon', h: 3.5, fly: 0.7, tint: 0xd8d0c0 }],
  [/\b(dragonling|whelp|hatchling)\b/, { mob: 'yellowdragon', h: 1.4, fly: 0.7 }],
  [/\b(wyvern|harrier|drake)\b/, { mob: 'yellowdragon', h: 2.4, fly: 0.9 }],
  [/\b(dragon|dragons|wyrm|fractal dragon|puff|yevaud)\b/, { mob: 'yellowdragon', h: 3.6, fly: 0.7 }],
  [/\b(imp|imps|gremlin|quasit|homunculus|goblin|goblins|kobold|kobolds)\b/, { mob: 'greendemon', h: 0.8 }],
  [/\b(balor|pit fiend|demon lord|archdevil)\b/, { mob: 'demon', h: 2.6 }],
  [/\b(demon|demons|devil|fiend|succubus|daemon|hellspawn)\b/, { mob: 'demon', h: 1.5 }],
  [/\b(wraith|wraiths|shade|shades|shadow|shadows|soul|souls|spectral|ghostly|void|being|feeling|nightmare)\b/, { mob: 'ghost', h: 1.4, fly: 0.3, tint: 0x6a5a8a }],
  [/\b(ghost|ghosts|spirit|spirits|spectre|specter|phantom|banshee|poltergeist|apparition|wisp|haunt|spook)\b/, { mob: 'ghost', h: 1.2, fly: 0.35 }],
  [/\b(flameskull|floating skull|skull)\b/, { mob: 'skull', h: 0.7, fly: 0.9 }],
  [/\b(troll|trolls)\b/, { mob: 'yeti', h: 2.8, tint: 0x7a9a6a }],
  [/\b(minotaur)\b/, { mob: 'cyclops', h: 2.8, tint: 0xa07858 }],
  [/\b(cyclops|ogre|ogres|giant|giants|ettin|ettins|ogrillon|behemoth|titan)\b/, { mob: 'cyclops', h: 3.0 }],
  [/\b(yeti|sasquatch|abominable|bigfoot|wendigo)\b/, { mob: 'yeti', h: 1.6 }],
  [/\bcactus\b/, { mob: 'cactus', h: 1.0 }],
  [/\b(beholder|eye tyrant|floating eye|gazer|alien)\b/, { mob: 'alien', h: 0.9, fly: 0.5 }],
  [/\b(cthulhu|kraken|octopus|squid|tentacle|horror|aberration|mind ?flayer|flayer|illithid|otyugh|morkoth|aboleth|chaos spawn)\b/, { mob: 'cthulhu', h: 1.3, fly: 0.3 }],
];

export function beastLook(name) {
  const n = String(name || '').toLowerCase();
  for (const [re, look] of BESTIARY) if (re.test(n)) return look;
  return null;
}
